### ISSUE TITLE
.NET 6 and v4 tooling

### ISSUE THREAD

**Issue by johnkors** [Azure/functions-action#105]
Hi,

According to [this page](https://github.com/Azure/Azure-Functions/wiki/V4-early-preview#net-60-isolated), one should be able to test Azure Functions on .NET 6 running in dotnet-isolated mode.

They mention publishing using the following command
```
$ func azure functionapp publish myapp --dotnet-version 6.0
```

Is it possible to provide that last parameter `--dotnet-version 6.0` somehow using this GH action?

**Comment by patelchandni** [comment]
@johnkors On creating new workflow, version '6.0.x' will be added by default depending on app version. For existing workflow, you can update the environment variable to '6.0.x' if your app is now upgraded to .NET 6.0. Please try and let us know. 

Here is an example of the line in workflow:

env:
  DOTNET_VERSION: '6.0.x'
