### ISSUE TITLE
Possible to have write access using zip deploy?

### ISSUE THREAD

**Issue by erwinsmit** [Azure/functions-action#106]
I'm currently trying to get a NextJS project working on azure functions. NextJS requires write access to the .next directory.  But as far as I can see using the "Azure/functions-action@v1" deploy command in the workflow yml only supports zip deploy. 

When using zip deploy the "RUN_FROM_PACKAGE" app settings needs to be set, that disables write accesss on the directories. 

Am I right in thinking that the only way would be to create a custom deploy script that uses a different strategy (e.g. web deploy?).

**Comment by balag0** [comment]
Correct, ZipDeploy will create a readonly packages that gets mounted at runtime at /home/site/wwwroot.
But other dirs are still writable. Ex: /tmp is always writable

**Comment by erwinsmit** [comment]
Thanks, I worked around it by placing the .next build outside of the wwwroot directory.
