### ISSUE TITLE
FA webspace location issue

### ISSUE THREAD

**Issue by jnus** [Azure/functions-action#107]
Problem:
When provisioning a function app in one resource group, with a dedicated App Service Plan located in a another resource group, the function app will get the webspace assigned corresponding to the ASP. For some reason this action cannot find FA's with seperate webspaces. 

How reproduce:
1. Create a ASP in resource group A
2. Create a FA in resource group B, but with the ASP in resource group A
3. Deploy to FA with Azure/functions-action@v1

Expected behavior:
One should be able to deploy to a function app with a different webspace.

**Comment by patelchandni** [comment]
@jnus The function app and the app service plan have to be under the same resource group. Please refer this article: https://docs.microsoft.com/en-us/azure/app-service/app-service-plan-manage#move-an-app-to-another-app-service-plan

**Comment by jnus** [comment]
@patelchandni  - so this is a limitation for the action right? We've been running shared ASP's in central ressource groups and decentralized function apps ( and web apps for that matter) for years and deploying to them. The article mentioned describes the boundaries for keeping resources, in this case app service plans, in the same webspace in order to access e.g. uploaded tls certificates etc - not that function apps and the app service plan should be in the same resource group for them to 'work'.
