### ISSUE TITLE
Automatic deployment failed

### ISSUE THREAD

**Issue by clintnetwork** [Azure/functions-action#112]
Hi,

You forget to set `include-prerelease: true` in your pre-build deployment file.

Otherwise I get this error:
```
Error: Could not find dotnet core version. Please ensure that specified version 6.0.x is valid.
```

Thanks

**Comment by patelchandni** [comment]
Thank you for the feedback. It is documented here: https://github.com/actions/setup-dotnet. This version is now released, but noted for pre-release versions in future.
