### ISSUE TITLE
Is not PowerShell function on Linux supported yet?

### ISSUE THREAD

**Issue by horihiro** [Azure/functions-action#117]
Currently, PowerShell function on Linux is GAed on Azure Functions runtime v4.
https://azure.microsoft.com/ja-jp/updates/generally-available-powershell-on-linux-os-in-azure-functions/

But this action [throws an error](https://github.com/Azure/functions-action/blob/master/src/handlers/resourceValidator.ts#L257-L259) when the function app is PowerShell on Linux.

**Comment by Michaelvsk** [comment]
And the [error message](https://github.com/Azure/functions-action/blob/2075fff27b0c048b05c1058147a55790565bc63a/src/handlers/resourceValidator.ts#L261) seems to be a Copy&Paste error and says `Windows` would not be supported.

**Comment by patelchandni** [comment]
Thank you for reporting, this is covered in PR: https://github.com/Azure/functions-action/pull/123
