### ISSUE TITLE
Allow single function deployment without overwriting all existing functions

### ISSUE THREAD

**Issue by ldenslow** [Azure/functions-action#130]
We have multiple functions in the same repo and the functions each have a yml file to handle scanning/deploying.  When we deploy function #2, it overwrites function #1 - we are struggling how to handle deploys of multiple functions in the same git repo to the same azure publishing profile - let us know if this action can be utilized without overwriting the functions already deployed?

**Comment by patelchandni** [comment]
This GitHub action is applied to the whole repo, so all functions in it will be affected if any changes were made.

**Comment by ldenslow** [comment]
Ok, thank you for your reply.  We chatted with Microsoft on this as well and received the direction to group functions into business categories that make sense to all deploy together.  So now we have a yml per repo and all functions in the repo will get deployed every time, even if only one function is modified.  Not ideal, but since the azure function app is the deployable unit, then we'll have to work with that!  Thanks for your triage!
