### ISSUE TITLE
Unable to deploy functions (Python 3.9 Linux Consumption Plan)

### ISSUE THREAD

**Issue by binaryPUNCH** [Azure/functions-action#150]
Hello. We have issues deploying from GitHub Actions with this runner. Python 3.9 Linux Consumption Plan. 

When we run `func azure functionapp publish alzvendingmachinedev --python` locally we are able to successfully deploy and see 5 functions on the Portal within the Function App.

However, when we deploy with this runner (latest v1.4.7) all functions get deleted and never reappear. The API call goes from working, to 404 Not Found and Application Insights shows `OperationNotFound` exceptions. When we redeploy locally the same API call works once again, and the 5 functions reappear on the portal.

The question is why the runner seemingly deletes all the functions without a sign of failure? Need help debugging. I tried both RBAC and PublishProfile, the end-result is the same.

Here are logs that don't say much, unfortunately. Is there a way to have them more verbose?

```
Run Azure/functions-action@v1.4.7
  with:
    app-name: alzvendingmachinedev
    package: ./
    respect-pom-xml: false
    respect-funcignore: false
    scm-do-build-during-deployment: false
    enable-oryx-build: false
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    pythonLocation: /opt/hostedtoolcache/Python/3.9.13/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.13/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.13/x64
    Python[2](https://github.com/REDACTED/PROJECT/runs/7877954211?check_suite_focus=true#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/REDACTED/PROJECT/runs/7877954211?check_suite_focus=true#step:6:3).9.13/x6[4](https://github.com/REDACTED/PROJECT/runs/7877954211?check_suite_focus=true#step:6:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.13/x[6](https://github.com/REDACTED/PROJECT/runs/7877954211?check_suite_focus=true#step:6:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.13/x64/lib
Using RBAC for authentication, GitHub Action will perform resource validation.
Successfully acquired site configs from function app!
Detected function app sku: Consumption
Successfully acquired app settings from function app (RBAC)!
Detected function app language: Python
Will archive ./ into /home/runner/work/_temp/temp_web_package_[7](https://github.com/REDACTED/PROJECT/runs/7877954211?check_suite_focus=true#step:6:7)70662064[8](https://github.com/REDACTED/PROJECT/runs/7877954211?check_suite_focus=true#step:6:8)[9](https://github.com/REDACTED/PROJECT/runs/7877954211?check_suite_focus=true#step:6:9)00389.zip as function app content
Will use WEBSITE_RUN_FROM_PACKAGE to deploy since RBAC is detected and your function app is on Linux Consumption.
Sync Trigger call was successful.
```

**Comment by patelchandni** [comment]
@binaryPUNCH Please try to deploy with following paramters:
scm-do-build-during-deployment: true
enable-oryx-build: true

**Comment by binaryPUNCH** [comment]
Hi @patelchandni. Thanks for the suggestion! Unfortunately, we get the same issue. And the logs look identical to my original post.

**Comment by patelchandni** [comment]
Hey @binaryPUNCH, Use publish profile (not RBAC) along with those parameters.

**Comment by binaryPUNCH** [comment]
Tried again with publish profile. Unfortunately the same outcome. More logs though.

```
Run Azure/functions-action@v1.4.7
  with:
    app-name: redacted
    package: ./
    scm-do-build-during-deployment: true
    enable-oryx-build: true
    publish-profile: ***
    respect-pom-xml: false
    respect-funcignore: false
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    pythonLocation: /opt/hostedtoolcache/Python/3.9.13/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.13/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.13/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.13/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.13/x64/lib
Successfully parsed SCM credential from publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Successfully acquired app settings from function app (with SCM credential)!
Will archive ./ into /home/runner/work/_temp/temp_web_package_43837672150002005.zip as function app content
Will use Kudu https://<scmsite>/api/zipdeploy to deploy since publish-profile is detected.
Setting SCM_DO_BUILD_DURING_DEPLOYMENT in Kudu container to true
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting SCM_DO_BUILD_DURING_DEPLOYMENT propagated to Kudu container
Setting ENABLE_ORYX_BUILD in Kudu container to true
Update using Client.updateAppSettingViaKudu
Response with status code 204
App setting ENABLE_ORYX_BUILD propagated to Kudu container
Package deployment using ZIP Deploy initiated.
Deploy logs can be viewed at https://redacted.scm.azurewebsites.net/api/deployments/ec78ac13-9bc3-4403-a802-97a8981cabed/log
Successfully deployed web package to App Service.
Response with status code 204
Response with status code 204
Response with status code 204
```

And then following the deploy logs link: [logs.txt](https://github.com/Azure/functions-action/files/9365753/logs.txt)

Any more ideas?

**Comment by binaryPUNCH** [comment]
It is interesting that Application Insights shows the `OperationNotFound` exception "Unable to match incoming request to an operation.". When I deploy from local dev the exact same API POST request succeeds without `OperationNotFound` exception.

I can actually tell now that on the Azure Portal, with your suggestions @patelchandni, I can now see my 5 functions within the Function App. That seems like progress!

**Comment by binaryPUNCH** [comment]
Still struggling. Any ideas from anyone?

**Comment by Duchynko** [comment]
It turned out that the `OperationNotFound` error was not related to the issue - it was caused by a default health check created by Application Insights.

**However, the deployment issue described by @binaryPUNCH still persists. After deployment, functions are not displayed in the portal and the API Management can not reach them.**

This is the deployment config
```yaml
- name: 'Run Azure Functions Action'
  uses: Azure/functions-action@v1.4.7
  with:
    app-name: "functionName"
    package: '.'
    publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
    scm-do-build-during-deployment: true
    enable-oryx-build: true
```

Debug logs: https://gist.github.com/Duchynko/8d390dae8152b1d6c57d8919b4d09750

Not sure if it's related but the `WEBSITE_ENABLE_SYNC_UPDATE_SITE` is set to `true` in the App Settings.

**Comment by Duchynko** [comment]
Looks very similar to https://github.com/Azure/functions-action/issues/110

**Comment by Duchynko** [comment]
Any recommendations or ideas on what could be causing this?

**Comment by patelchandni** [comment]
@binaryPUNCH please verify your folder structure at "./" location. Here is the required structure: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level#folder-structure

**Comment by patelchandni** [comment]
@Duchynko and @binaryPUNCH, also share your workflow to validate steps before deploy action.

**Comment by Duchynko** [comment]
@patelchandni thanks for the tip. We've found the problem.

As we're hosting our code in a monorepo, we are specifying dynamic `defaults.run.working-directory` per Azure Function/application. We assumed that the `package` argument in `Azure/functions-action` is automatically picking that up but it seems like it doesn't. 

After changing the value of the `package` argument from `.` to `./path-to/function`, everything started to work as expected.

```yaml
jobs:
  build-deploy:
    defaults:
      run:
        working-directory: "path-to/function" 

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.4.7
      with:
        app-name: ${{ inputs.azure_functionapp_name }}
        package: '.' # The package argument didn't consider "defaults.run.working-directory"
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
```

Is that intended behavior?

**Comment by patelchandni** [comment]
@Duchynko Yes, it is a requirement to provide the path to the directory that has project root. The documentation and sample workflows also state to set it to your project root or else it will default to the repository root.
