### ISSUE TITLE
Warning in workflow about nodejs version

### ISSUE THREAD

**Issue by johan-lindqvist** [Azure/functions-action#155]
It seems that GitHub is deprecating nodejs12 which gives warnings when using this action in a workflow:
![image](https://user-images.githubusercontent.com/1523775/195315569-2640c056-eca6-40f6-9ee2-4e352603eb52.png)

Warning in text: 
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/arm-deploy, azure/functions-action
```

**Comment by jerimiahwelch** [comment]
+1 for this.

**Comment by patelchandni** [comment]
Updated in latest released v1
https://github.com/Azure/functions-action/releases/tag/v1.4.8
