### ISSUE TITLE
Warning in workflow about `set-output` command

### ISSUE THREAD

**Issue by amitak** [Azure/functions-action#156]
GitHub has deprecated `set-output` command and will disabled it soon.
Warning seen in the workflow:
```    The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/    ```

**Comment by patelchandni** [comment]
@amitak This warning is for which action? Is it under functions-action or any other action?

**Comment by vishalmamidi** [comment]
@patelchandni it is under functions-action, we should be updating `@actions/core` in `package.json` to above `v1.10.0`

<img width="184" alt="image" src="https://user-images.githubusercontent.com/12382861/199684653-f9514bb0-33f4-4f0e-b7ed-35002ae1082f.png">

and in `actions.yml` update to use `node16 `

<img width="134" alt="image" src="https://user-images.githubusercontent.com/12382861/199685291-893a8d87-47f5-4f98-bdb9-0b6c8696974a.png">
 
 
 I can create a PR if that helps

**Comment by patelchandni** [comment]
Updated in latest released v1
https://github.com/Azure/functions-action/releases/tag/v1.4.8
