### ISSUE TITLE
Oryx build keeps failing during deployment

### ISSUE THREAD

**Issue by RJJ95** [Azure/functions-action#159]
Hi there,

I've created a Linux Function App in a Consumption plan. I'm currently deploying using a connection to Github. For some reason every time I'm trying to deploy it fails with the following message:

Generating summary of Oryx build
Deployment Log file does not exist in /tmp/oryx-build.log
The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
Deployment Failed. deployer = GITHUB_ZIP_DEPLOY deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_01[78](https://github.com/RJJ95/azure-functions-linux/actions/runs/3318478928/jobs/5482519561#step:5:79)7711583626872.zip as ZipDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!

Now I've tried deploying using the following ways:
- Via VS Code
- Via the command line
- Via Github Actions

I keep getting the same error message. Also, the Azure Function is about as fresh as it can get. Newly created from the Azure Portal and als tried from the command line.

The first time I deploy it works, but the afterwards it keeps failing. How should I proceed here?

**Comment by patelchandni** [comment]
@RJJ95 Which language you're using? Also, share your GitHub workflow.
If you already have build step in your pipeline so no need for remote build. So please make these changes and redeploy:
1. Set function app settings to:
      ENABLE_ORYX_BUILD: false
      SCM_DO_BUILD_DURING_DEPLOYMENT: false
2. In the .yaml pipeline for functions-action set:
      scm-do-build-during-deployment: false
      enable-oryx-build: false

**Comment by t1m0** [comment]
Hi,

I face a similar issue, trying to deploy a javascript function.
First I tried creating the workflow.yml based on the tutorial provided - since that failed, I discovered I can create the yml in the deployment center of my function in azure.

However both function looked very similar and both fail with the same reason.

Here the link to the .yml generated by azure - https://github.com/t1m0/master-thesis-data-function/blob/main/.github/workflows/main_master-thesis-data-function.yml

**Comment by t1m0** [comment]
I also tried the settings provided by you - without success

**Comment by patelchandni** [comment]
Hi @t1m0 , your issue is totally different as there is a warning that the AzureWebJobsStorage connection string is not set up for your app: https://github.com/t1m0/master-thesis-data-function/actions/runs/3384044303/jobs/5620557675#step:5:16
Because of this the deployment is failing so add the AzureWebJobsStorage app setting to fix it.

**Comment by t1m0** [comment]
Hi @patelchandni ,

thanks - this solved my issue! sorry I overlooked this warning.

**Comment by godjiberry** [comment]
Hi, 

I'm totally new to this and I'm also receiving similar error to the aboves. Can someone walk me step by step how to fix it?
Thank you in advance.

3:43:11 PM openaisecondtry: Deployment Log file does not exist in /tmp/oryx-build.log 
3:43:11 PM openaisecondtry: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build 
3:43:11 PM openaisecondtry: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build. 
3:43:24 PM openaisecondtry: Deployment failed.

**Comment by leanemac** [comment]
> 

Hi there, 

I'm getting the exact same error while trying to deploy my Python function. 
Anyone can help? Thanks

**Comment by CSLAFan** [comment]
Hi, I am getting the same error as well. It worked perfectly when I deployed the function for the first time. Did some small change in function and redeployment is giving error.

**Comment by zub3rrr** [comment]
> I getting the same error like "The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build". ![image](https://private-user-images.githubusercontent.com/26666783/246816606-c838ee28-8472-4e5f-add5-3604be289d42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMDA0NzEsIm5iZiI6MTcwMzMwMDE3MSwicGF0aCI6Ii8yNjY2Njc4My8yNDY4MTY2MDYtYzgzOGVlMjgtODQ3Mi00ZTVmLWFkZDUtMzYwNGJlMjg5ZDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAyNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYTAyZWJmYjMwZTgwNmU0ODgyODIyYjE4ZTE1ZGNkZWIyNTFjY2M2ZmYwZjFjZWM5Mzc2NjQ3YjBlZmE5YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3SuLhePyHabnChqN1mg0uVKytW-xCmfYa6eyrBFcIxQ)
> 
> And resolved through:
> 
> 1. Delete the function app in Azure Portal.
> 2. Create Function App in VSCode - Azure - Resources - Create Function App in Azure.
>    ![image](https://private-user-images.githubusercontent.com/26666783/246816689-088acf56-416a-48e5-8d95-93e28076ae25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMDA0NzEsIm5iZiI6MTcwMzMwMDE3MSwicGF0aCI6Ii8yNjY2Njc4My8yNDY4MTY2ODktMDg4YWNmNTYtNDE2YS00OGU1LThkOTUtOTNlMjgwNzZhZTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAyNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTkxOTQ1NTlkMzg1ZGRjNzQ3NzVlNzIyN2Q0Njc1YmQ5MzJiOWRkNzNjOWE4MzlkYTBlZTFiNDQ1YWI4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.auK8aD3-oBLOE8xPi15BOFOZWw7y62kKtzrq4Gq4i5Y)
> 
> Then I can deploy.



@auzurdragon , Thanks it worked for me

**Comment by zub3rrr** [comment]
Points to be considered while deploying Azure functions :
1. All extensions are installed (specially : Azure Function , Azure Account , Azure Resource)
2. Check Storage Account connection string in AzureWebJobsStorage = connection string (connection string can be found in access key section of affiliated storage account)
3. If deploying from VS code , try to create azure function app from Azure account extension panel itself (Try to select Create Azure Function in App .. Advance option).
4. For understanding of process , try first to deploy simple program such as Hello World , Print current datetime etc.

**Comment by parhammmm** [comment]
Oryx build is very opaque fails randomly and requires multiple retries to build and there are no logs apart from Deploys > Logs > commit > show Logs, which is not very informative.

I think the answer is no, but is there anywhere that shows the full oryx build log?
