### ISSUE TITLE
Linux CD of 'Azure/functions-action@v1' fails

### ISSUE THREAD

**Issue by seniakalma** [Azure/functions-action#161]
Hi,
I'm trying to set a CD Github action for my Node (Linux) function (by the following [guide](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=javascript)), but I keep getting the following error:

> Run Azure/functions-action@v1
Successfully parsed SCM credential from publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Successfully acquired app settings from function app (with SCM credential)!
Will archive . into /home/runner/work/_temp/temp_web_package_1026308224673278.zip as function app content
Will use Kudu https://<scmsite>/api/zipdeploy to deploy since publish-profile is detected.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDepoy : WEBSITE_RUN_FROM_PACKAGE in your function app is set to an URL. Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app.
Error: Deployment Failed!

When trying to deploy my Azure function.
I've tried removing the 'WEBSITE_RUN_FROM_PACKAGE' value from the function settings but it kept coming up on each CD re-run.
I've also tried adding a "WEBSITE_RUN_FROM_PACKAGE": "1", entry in my 'local.settings.json' file.
Attached is the CD.yml file used (in the .github/worflows dir of my repo)
Would be happy to try any idea to make it work.

Thanks,
Arseni
[CD.yml.txt](https://github.com/Azure/functions-action/files/9956057/CD.yml.txt)

**Comment by patelchandni** [comment]
@seniakalma Is it on consumption plan? 
Please remove the 'WEBSITE_RUN_FROM_PACKAGE' app setting from the portal and then rerun the workflow again.
