### ISSUE TITLE
Incompatibility with PEP 517

### ISSUE THREAD

**Issue by bkazour** [Azure/functions-action#163]
Hello
When trying to deploy Azure functions that has part of the requirements a python library that uses PEP 517 such as **arcgis**, the build is successful, however the deployment fails with the below error
ERROR: Could not build wheels for **gssapi** which use PEP 517 and cannot be installed directly

I tried to manually install **gssapi** in previous steps by running the below right before deploy-to-function step.

```
      - name: upgrade wheel
        run: pip install --upgrade pip setuptools wheel
      - name: Install kbr5
        run: sudo apt-get install libkrb5-dev
      - name: install gssi
        run: sudo pip install gssapi --no-cache-dir
```

Those steps are successful, but the deployment step still fails with that error.
Any advice on this is appreciated
Thank you

**Comment by patelchandni** [comment]
@bkazour Please share the deploy step to check parameters used. Are you using remote build and can you turn it off if not needed?
