### ISSUE TITLE
Error deploying to Azure Function App service

### ISSUE THREAD

**Issue by will300** [Azure/functions-action#168]
Hi,
I am using the functions-action v1 GitHub action to deploy to the Azure Function App service, and am getting the following error -

Step Details –
--------------------------------------------------------------------------------------------------------------------------------------------------
- name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

Error Message -
--------------------------------------------------------------------------------------------------------------------------------------------------
Generating summary of Oryx build
Deployment Log file does not exist in /tmp/oryx-build.log
The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
Triggering recycle (preview mode disabled).
Linux Consumption plan has a 1.5 GB memory limit on a remote build container.
To check our service limit, please visit https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits
Writing the artifacts to a squashfs file
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /home/site/artifacts/functionappartifact.squashfs, block size 131072.

[==========-                                                   ] 1200/6677  17%
[================|                                             ] [180](https://github.com/AXA-Venture-Partners/Anabot/actions/runs/4123835090/jobs/7122341328#step:5:181)0/6677  26%
[=============================================================|] 6677/6677 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 42239.93 Kbytes (41.25 Mbytes)
	30.36% of uncompressed filesystem size (139119.65 Kbytes)
Inode table size 65659 bytes (64.12 Kbytes)
	28.87% of uncompressed inode table size (227400 bytes)
Directory table size 66076 bytes (64.53 Kbytes)
	35.44% of uncompressed directory table size ([186](https://github.com/AXA-Venture-Partners/Anabot/actions/runs/4123835090/jobs/7122341328#step:5:187)420 bytes)
Number of duplicate files found 456
Number of inodes 7018
Number of files 6214
Number of fragments 507
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 804
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
Creating placeholder blob for linux consumption function app...
Malformed SCM_RUN_FROM_PACKAGE when uploading built content.

Generating summary of Oryx build
Deployment Log file does not exist in /tmp/oryx-build.log
The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
Deployment Failed. deployer = GITHUB_ZIP_DEPLOY deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_03[196](https://github.com/AXA-Venture-Partners/Anabot/actions/runs/4123835090/jobs/7122341328#step:5:197)6780744437484.zip as ZipDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!

---------------------------------------------------------------------------------------------------------------------------------------------------

The app is active and running on Azure. Some details are as follows:

Azure Configuration
---------------------------------------------------------------------------------------------------------------------------------------------------
Location: West Europe
Operating System: Linux
Runtime Version: 4.15.1.1
Status: Ready
Zone Redundant: Disabled
ENABLE_ORYX_BUILD: 1
FUNCTIONS_EXTENSION_VERSION: ~4
FUNCTIONS_WORKER_RUNTIME: python
SCM_DO_BUILD_DURING_DEPLOYMENT: 1
App Service authentication: Enabled
Restrict access: Require authentication
Unauthenticated requests: Return HTTP 401 Unauthorized
Token store: Enabled

---------------------------------------------------------------------------------------------------------------------------------------------------

And the repo I'm trying to deploy has roughly the following file structure:

GitHub Repo
---------------------------------------------------------------------------------------------------------------------------------------------------
├── .github
│ ├── workflows
│ │ └── config.yml
├── bin
│ ├── dir1
│ │ ├── file1.py
│ │ ├── file2.py
│ │ └── init.py
│ ├── dir2
│ │ ├── file1.py
│ │ ├── file2.py
│ │ └── init.py
│ └── init.py
├── host.json
├── local.settings.json
├── requirements.txt
├── otherfile1
└── otherfile2

**Comment by patelchandni** [comment]
@will300 Is app setting AzureWebJobsStorage set with correct connection string for your function app?

**Comment by dvegaeygds** [comment]
@patelchandni same issue 
![image](https://user-images.githubusercontent.com/127428374/233763813-21ffb618-1551-43ea-bef7-3c196abd4033.png)

after adding the AzureWebJobsStorage  config with the blob conn string are running ok but with nothing to see on the azure portal:
![image](https://user-images.githubusercontent.com/127428374/233764764-b9333529-6d43-4419-a284-e7bcfe46aa04.png)

**Comment by patelchandni** [comment]
@dvegaeygds Do you see AzureWebJobsStorage app setting in the portal? After adding it, please restart your app and then redeploy.

**Comment by dvegaeygds** [comment]
@patelchandni I did, but still doesn't work I re created the function and now is ok. weird?

**Comment by nstein-gpjoule** [comment]
I got the same error, in my case the app wasn't running. After starting the App again the deployment was successful.
