### ISSUE TITLE
WEBSITE_RUN_FROM_PACKAGE value reset to 0

### ISSUE THREAD

**Issue by fleed** [Azure/functions-action#173]
I'm trying to deploy a .NET 7 Azure function using the GitHub action.
As part of the build workflow, I'm publishing the application using `dotnet publish`, saving it in a zip file and storing it into Azure storage.
In the deployment workflow, I'm downloading the archive, extracting it and running the GitHub action (using `Azure Login` for authentication, so without a publish profile).

The entire flow works if I manually set back the `WEBSITE_RUN_FROM_PACKAGE` settings to **0**.
I've noticed that the GitHub action sets the value to **1**, and then the triggers are not recognized.
Is there a flag in the action to use in this case?

Useful information:
- **Platform**: `64bit`
- **.NET Version**: `.NET 7 Isolated`

Other application settings:

- FUNCTIONS_EXTENSION_VERSION: ~4
- FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
- WEBSITE_RUN_FROM_PACKAGE: 0 (before being changed by the deployment)

**Comment by patelchandni** [comment]
@fleed when using azure login with this action, the default behavior is to set WEBSITE_RUN_FROM_PACKAGE=1 if not present. So, to override you will have to add WEBSITE_RUN_FROM_PACKAGE=0. 
I'm more curious to know why the triggers are not found with WEBSITE_RUN_FROM_PACKAGE=1. 
1. Is your folder structure correct inside the zip file? Refer: https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v4%2Ccmd#functions-class-library-project
2. Are you trying to perform a remote build or run any post deployment scripts?

**Comment by fleed** [comment]
Hi @patelchandni , thank you for your answer.
The problem was that we were zipping the output of `dotnet publish` but that was not including the hidden `.azurefunctions` folder.
After forcing the archiving of the hidden folder the endpoints are correctly found.

You mentioned that I should add `WEBSITE_RUN_FROM_PACKAGE=0`: could you please give some more info about this step? where exactly should I specify it?

Thank you
