### ISSUE TITLE
Deployment Log file does not exist in /tmp/oryx-build.log

### ISSUE THREAD

**Issue by hungnguyen9921** [Azure/functions-action#187]
Hi, when I try to deploy my Azure function it shows this error for me and I fix this by the way disable ENABLE_ORYX_BUILD to false and set SCM_DO_BUILD_DURING_DEPLOYMENT to false. After that, my function deploys successfully but it does not install all requirements in requirements.txt file

**Comment by patelchandni** [comment]
@hungnguyen9921 Please set SCM_DO_BUILD_DURING_DEPLOYMENT=true to install requirements. 
Usually, Deployment Log file does not exist in /tmp/oryx-build.log is a warning and not an error. Please send the exact error you see or a screenshot.
