### ISSUE TITLE
(node:1523) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by cobriensr** [Azure/functions-action#223]
Run Azure/functions-action@v1.5.1
Successfully parsed SCM credential from publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
(node:1523) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by patelchandni** [comment]
Thanks for reporting. Part of PR: https://github.com/Azure/functions-action/pull/234
