### ISSUE TITLE
Azure/functions-action@v1 runs successfully, but function is not updated 

### ISSUE THREAD

**Issue by glenpennington-8451** [Azure/functions-action#232]
Our workflow is configured to download site packages in the build phase - the deploy should be a straight forward copy. The build and deploy jobs complete successfully and I see the functions restart in Datadog logging. However, the changes have not taken effect - I have confirmed through the Azure portal that the previous function code is still present.

The branch I am attempting to deploy: https://github.com/8451LLC/map-campaign-intake-functions/tree/feature/effocomms-35846
GH Action Log: https://github.com/8451LLC/map-campaign-intake-functions/actions/runs/9214274064

I have also tried having the deploy step process the build, this fails as pip does not find all packages in requirements.txt.

**Comment by patelchandni** [comment]
Correct the package version in the requirement.txt to resolve build error.
