### ISSUE TITLE
How to set NODE_ENV to production?

### ISSUE THREAD

**Issue by screendriver** [Azure/functions-action#24]
I want to deploy a [GraphQL Apollo server](https://www.apollographql.com) as an Azure function. Therefore I'm using [apollo-server-azure-functions](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-azure-functions). Unfortunately you can open the GraphQL Playground in my deployed Azure function.

When `NODE_ENV` is set to `production`, GraphQL Playground (as well as introspection) is disabled as a production best-practice. Is it possible to set that somehow with this GitHub action?

**Comment by ahmedelnably** [comment]
This action doesn't support setting app settings or environment variables
You will need to set these up using the Azure Portal or other management tools
