### ISSUE TITLE
GitHub Action failed with WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by zaaraungkam** [Azure/functions-action#248]
Deploy Azure function app with action 'function-actions' with failed.

`Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDepoy : WEBSITE_RUN_FROM_PACKAGE in your function app is set to an URL. Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app.
Error: Deployment Failed!`

`      - name: Deploy ${{env.APP_NAME}}
        uses: azure/functions-action@v1.5.2
        with:
          app-name: ${{env.AZURE_FUNCTION_APP_NAME}}-${{env.Environment}}
          remote-build: false`

**Comment by zaaraungkam** [comment]
issue already fixed with change WEBSITE_RUN_FROM_PACKAGE in portal azure from an url to '1'

**Comment by 4eRTuk** [comment]
OMFG if someone is reading this in Aug 2025, try setting WEBSITE_RUN_FROM_PACKAGE to 'true' instead of '1'. It is insane, undocumented and not backward compatible, but I spent 1.5 hour of my life trying to figure out why it works on one account and not on another.
