### ISSUE TITLE
set-env deprecation message

### ISSUE THREAD

**Issue by timheuer** [Azure/functions-action#42]
My workflow is now showing me warnings regarding the deprecation of `set-env` https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.  Need to upgrade to latest core toolkit 
![image](https://user-images.githubusercontent.com/4821/95141645-97b05700-0726-11eb-88db-24b40cfceba3.png)

**Comment by cocallaw** [comment]
Also receiving this warning when deploying .net core function

**Comment by AmrutaKawade** [comment]
PR is merged. You can use v1 tag

**Comment by cocallaw** [comment]
@AmrutaKawade can confirm that notifications are no longer present when using the following -
 `Azure/functions-action@v1.1.6`
`Azure/functions-action@v1`
