### ISSUE TITLE
Change the name of the action to fit the purpose

### ISSUE THREAD

**Issue by shibayan** [Azure/functions-action#45]
It's hard to understand this as an Action that deploys to Azure Functions by its current name. In fact, I didn't understand what Action does.

I think a name like `Azure/functions-deploy` would be more appropriate for the real world.

**Comment by aksm-ms** [comment]
@N-Usha can you please take a look at it?

**Comment by N-Usha** [comment]
Thanks @shibayan.. Fair feedback.. but renaming the action now could break the existing set of users and their workflows... Hence we'll consider in future if we could rename this in future with least disruption to developers.
