### ISSUE TITLE
All my function apps have stopped deploying since 16th November

### ISSUE THREAD

**Issue by nikkh** [Azure/functions-action#49]
I have a couple of workflows that use azure/functions-action@v1 that have stopped working in the last day or so i do recall mention of set-env deprecation in the logs a few days ago but I was focusing on something else so didn't follow-up.

I have a number of applications that use this action, and as it happens they have all stopped working overnight. I suspect they may be related to this. There have been no other relevant changes in my repos. Take a look at these:

https://github.com/nikkh/heracles-ai/runs/1411302955
https://github.com/nikkh/heracles-ai/runs/1406173184
https://github.com/nikkh/zodiac/runs/1407855810

This is a log from a successful run for the first failure above:

https://github.com/nikkh/heracles-ai/runs/1397235421

Unfortunately, since I am mainly developing the workflows I have a cleanup job that deletes successfully deployed azure resources so I cant go back and look at (e.g.) kudo logs for successful deployments.

I'm an MS-FTE you can ping nhill to get in touch.

**Comment by nikkh** [comment]
I spoke with one of the GitHub team and we agreed although not directly related to set-env it may be one of the dependencies uses it and that is causing this error?

**Comment by aksm-ms** [comment]
@nikkh node module upgrade to resolve set-env issue was done in 1.1.6 and azure/functions@v1.1.6 is working fine. we will look into the issue in v1

**Comment by aksm-ms** [comment]
@Hazhzeng can you please take a look at this issue? workflows with v1 which points to v1.1.7 are failing.

**Comment by Hazhzeng** [comment]
Looking into it now

**Comment by Hazhzeng** [comment]
While I'm investigating and making a fix, @nikkh can pin back to v1.1.6 and see if it mitigates this issue.

**Comment by Hazhzeng** [comment]
Hi @nikkh,

I've released a new version https://github.com/Azure/functions-action/releases/tag/v1.1.8 and updated the v1 tag, please check if the GitHub action is working as expected now.

**Comment by Hazhzeng** [comment]
As per https://github.com/Azure/functions-action/issues/48, this issue should be fixed now.
Feel free to reopen the ticket if this issue still exists in your case.
