### ISSUE TITLE
Include AppSettings

### ISSUE THREAD

**Issue by johnkors** [Azure/functions-action#51]
Hi, 

how do I include any Github secrets (configurations for the function) that I would like to make use of in the Function?

**Comment by aksm-ms** [comment]
@johnkors Are you looking for instructions on how to set a secret variable and use it in a workflow?

**Comment by johnkors** [comment]
No. I would like to push a config setting to Azure (a config setting for the Azure Function, like a a connectionString or similar).

**Comment by johnkors** [comment]
As far as I see, [action.yml](https://github.com/Azure/functions-action/blob/master/action.yml) does not allow for setting custom `appSettings` to be published with the function, but you do update [appSettings changes further down in the code](https://github.com/Azure/functions-action/blob/d6d2dee206803a47a889462be6308596a3a003e5/src/interfaces/IAppSettings.ts#L1). I guess my feature request is then to be able to append to  `appSettings` with whatever config (key-value pairs) I please.

**Comment by arjgupta** [comment]
@johnkors you can use the [Azure App service settings](https://github.com/marketplace/actions/azure-app-service-settings) to set app settings for your function app.

**Comment by arjgupta** [comment]
@johnkors did you try using the 'Azure App service settings' action to set app settings for your function app ?

**Comment by arjgupta** [comment]
@johnkors i am closing this issue. Please reopen if this is not what you were looking for.
