### ISSUE TITLE
[Feature Request] Add ability to deploy using Azure Credentials, Resource Group Name and Function Name (without publish profile)

### ISSUE THREAD

**Issue by ma3yta** [Azure/functions-action#54]
https://devkimchi.com/2020/11/05/deploying-azure-functions-via-github-actions-without-publish-profile/

**Comment by aksm-ms** [comment]
@N-usha Can you please take a look at it?

**Comment by maksimetsa** [comment]
@github-actions thanks Cap

**Comment by maksimetsa** [comment]
@github-actions thanks Cap

**Comment by maksimetsa** [comment]
@github-actions thanks Cap

**Comment by maksimetsa** [comment]
@github-actions thanks Cap
