### ISSUE TITLE
Failed to fetch Kudu App Settings

### ISSUE THREAD

**Issue by loganmc10** [Azure/functions-action#57]
```
Run Azure/functions-action@v1
##[Initialize]
##[ValidateParameter]
Successfully parsed SCM credential from old publishProfile
##[ValidateAzureResource]
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Error: Execution Exception (state: ValidateAzureResource) (step: Invocation)
Error:   When request Azure resource at ValidateAzureResource, Get Function App Settings : Failed to acquire app settings (SCM)
Error:     Failed to fetch Kudu App Settings.
Not Found (CODE: 404)
Error:       Error: Failed to fetch Kudu App Settings.
Not Found (CODE: 404)
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:62:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Deployment Failed!
```

I'm sorry the repo is a private repo so I can't share the function code, but this is something was working some time ago, and now my latest builds are getting this error

**Comment by balag0** [comment]
This doesn't look related to the code. I assume retry also doesnt work? Recommend restarting the app as well in case that helps.

Please share the app name and we will investigate either way. You can use 
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately if needed.

**Comment by loganmc10** [comment]
I tried restarting the app, no luck. The name of the app is ```nocevents```

**Comment by Hazhzeng** [comment]
Hi @balag0, This morning, another support eng contacting me the 404 issue happens in UK South (ln1). Yesterday, @divyagandhii just reminded me that the kudulite container never enabled SIGTERM eviction. Could that be an issue where our customers are seeing 404?

**Comment by divyagandhii** [comment]
SIGTERM evictions are completely unrelated to client side 404s.

**Comment by loganmc10** [comment]
FWIW, my app was a consumption app. I tried completely re-creating the app, same problem. However I changed the app to a basic plan, instead of consumption based, and now it's working.

I don't know for sure if these things are related or if it was just a coincidence.

**Comment by balag0** [comment]
Thanks for the additional details. Could you provide the name of the 2nd app you created as well. I am taking a look at this now.

**Comment by balag0** [comment]
@loganmc10 Found the issue and applied a mitigation. The issue was specific to consumption sku so your experience is not surprising. Could you try again and update please. 

There is a small possibility the app you are using might land on a bad worker (not all bad workers are completely drained at this time) but I expect this to be rare. Restarting the app will switch the app to a different worker in case you do hit the issue.

**Comment by arjgupta** [comment]
@loganmc10 is the issue resolved for you ??

**Comment by loganmc10** [comment]
Yes, I haven't gone back to the consumption app, but everything is working for me now, and it sounds like the root issue was probably resolved

**Comment by loganmc10** [comment]
@balag0 I'm running into this again, again with a consumption app:
```
Run Azure/functions-action@v1
Successfully parsed SCM credential from old publishProfile
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Error: Execution Exception (state: ValidateAzureResource) (step: Invocation)
Error:   When request Azure resource at ValidateAzureResource, Get Function App Settings : Failed to acquire app settings (SCM)
Error:     Failed to fetch Kudu App Settings.
Not Found (CODE: 404)
Error:       Error: Failed to fetch Kudu App Settings.
Not Found (CODE: 404)
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:62:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Deployment Failed!
```

**Comment by balag0** [comment]
@loganmc10 Please open a new issue with details on the appname/ timestamps and tag me. Thanks
Will leave this incident closed.
