### ISSUE TITLE
Support Run from Package feature

### ISSUE THREAD

**Issue by maximivanov** [Azure/functions-action#58]
First, thanks for your work! This was a long awaited Github action and finally we can run both CI and CD workflows in Github 🚀.

If I understand it correctly, currently the Action uses zip deploy strategy where it's copying files to the `/home/site/wwwroot` directory on the Function App host machine. This is where the runtime will read files from.

I wonder if you're planning to add support for [Run from package](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package)? From what I gather it's a preferred way to run FAs since it has some advantages (atomicity, faster cold starts, etc) over normal copy-to-home-folder strategy.

Besides, run from package seems to be ON by default when deploying with Azure Functions Core Tools. It'd be great to see consistency among the tools!

**Comment by aaronadamsCA** [comment]
Hey @maximivanov, I currently use this action to deploy Node.js function apps to Windows serverless (consumption) plans.

If you set `WEBSITE_RUN_FROM_PACKAGE=1` in the function app, and then deploy with this action, it runs from a package. My `wwwroot/` contains only `host.json`; my `data/SitePackages/` is full of ZIP files, one per deploy. My cold starts are fast, too. So it's definitely running from a ZIP file.

The team that supports this action seems to be spread way too thin, as evidenced by your question sitting unanswered for two months when the answer is literally just "yes."

I hope @github will consider giving @N-Usha enough resources to build this critical piece of infrastructure, because it needs a lot more attention than it gets today!

**Comment by maximivanov** [comment]
@aaronadamsCA I will try that thanks. Still, if I use Azure Functions Core Tools, and do a `publish` on a fresh function app (not having `WEBSITE_RUN_FROM_PACKAGE` app setting), it will set the `WEBSITE_RUN_FROM_PACKAGE=url`, i.e. run from package is the default deployment method there.

Here it's not. I wish it was consistent across all the tools.

**Comment by maximivanov** [comment]
Inspired by @aaronadamsCA's success, I gave it a try and here are the results. Things are definitely not as bright in the Linux land. 😅 

### Linux Consumption

◉ I created a fresh Function App with `WEBSITE_RUN_FROM_PACKAGE=1` app setting. 
Published the code with the Github Action. All action's steps succeeded. 

**Result:** code was not deployed. There are no files in the App Files section and no functions in the Functions in the Portal.

In fact, I realized I already opened an issue to update Azure docs to reflect the fact that Linux Consumption does not support `WEBSITE_RUN_FROM_PACKAGE=1`: https://github.com/Azure/azure-functions-core-tools/issues/2356

◉ I then removed the `WEBSITE_RUN_FROM_PACKAGE=1` app setting and ran the Github Action again. All action's steps succeeded. 

**Result:** the code was deployed. I assume the files were placed directly in the `/home/site/wwwroot`.

### Linux Premium

◉ I created a new Function App with `WEBSITE_RUN_FROM_PACKAGE=1` app setting in a EP1 hosting plan. 
Published the code with the Github Action. All action's steps succeeded. 

**Result:** code was deployed and `WEBSITE_RUN_FROM_PACKAGE=1` was respected. There is a zip file in `/home/data/SitePackages` as well as a `packagename.txt` referencing it.

◉ I created a new Function App without `WEBSITE_RUN_FROM_PACKAGE=1` app setting in a EP1 hosting plan. 
Published the code with the Github Action. Run Azure Function action failed with the following error:

```text
Running post deployment command(s)...
Triggering recycle (preview mode disabled).
Deployment successful.
Error: Failed to deploy web package to App Service.
Successfully updated deployment History at https://azfunccdgh-dev-function-app.scm.azurewebsites.net/api/deployments/9fd96845276b354c89a1ddee653c4a2a963babb81613163325529
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_33195088267481565.zip as ZipDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!
```

*There was no error description in the referenced logs*

**Result:** despite the error, the code was deployed and worked. I could see files under `/home/site/wwwroot`. There was no `/home/data/SitePackages` directory.

I then ran the Action once again and there was no error that time. Not sure what it was.

### Summary

Linux Consumption: currently Functions Action deploys directly to the `wwwroot` folder. It should use `WEBSITE_RUN_FROM_PACKAGE=<url>` method by default instead (with configuration option to override if needed). Run from package is the recommended deployment method and it is the default in Azure Functions Core Tools.

Linux Premium: currently Functions Action respects the `WEBSITE_RUN_FROM_PACKAGE` setting. This makes sense. It's still inconsistent with Azure Functions Core Tools' defaults (`WEBSITE_RUN_FROM_PACKAGE=<url>`) though. But that's probably a part of a bigger discussion of unifying the deployment tooling.

**Comment by aaronadamsCA** [comment]
Oh boy. I've been waiting for a while for Linux consumption plans to finally make their way to Canada. Thanks for sharing, I would not have known about this at all! Glad I didn't get the opportunity to waste my time.

This does seem sadly representative of the state of Azure Functions as a self-serve platform. My functions are written in TypeScript, built with GitHub Actions, and deployed to Azure. It's a full Microsoft stack, and every day it feels like a mess, with no real signs of hope.

Azure is not for the faint of heart. 😬

**Comment by ss185427** [comment]
I'm facing the same issue after creating an Azure Function in Go using instructions from [here](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-other). Deployment works fine on a Linux Consumption plan with Azure Functions Core Tools (via Azure Functions VS Code extension).
Deployment fails from GitHub Actions with as WEBSITE_RUN_FROM_PACKAGE is set to URL. If WEBSITE_RUN_FROM_PACKAGE is deleted then deployment succeeds in GitHub Actions but the Azure Function doesn't work.

**Comment by ingoschaal** [comment]
Hi
I also have a similar problem
Deployment from my local machine works fine, function is deployed and can be used.
Deployment fails from GitHub Actions with the error:

`
Run Azure/functions-action@v1.4.0
Successfully parsed SCM credential from old publish-profile format.
Using SCM credential for authentication, GitHub Action will not perform resource validation.
Sucessfully acquired app settings from function app (with SCM credential)!
Will archive ././build/azure-functions/example/example into /home/ghrunner/actions-runner-1/_work/_temp/temp_web_package_asdfasdf.zip as function app content
Will use Kudu https://<scmsite>/api/zipdeploy to deploy since publish-profile is detected.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDepoy : WEBSITE_RUN_FROM_PACKAGE in your function app is set to an URL. Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app.
Error: Deployment Failed!
`

When WEBSITE_RUN_FROM_PACKAGE is removed, the same error occurs.
I am happy about every hint, thanks

**Comment by eprokhor** [comment]
Getting same error:
Error: ENOENT: no such file or directory, stat '/home/site/wwwroot/node_modules/.bin/tsc'
An error has occurred during web site deployment.
Kudu Sync failed
\n/opt/Kudu/Scripts/starter.sh "/home/site/deployments/tools/deploy.sh"
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_6568705682761959.zip as ZipDeploy content
Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
Error: Deployment Failed!

**Comment by primenumsdev** [comment]
I just faced with the same error:

```
Error:   When request Azure resource at PublishContent, zipDepoy : WEBSITE_RUN_FROM_PACKAGE in your function app is set to an URL. Please remove WEBSITE_RUN_FROM_PACKAGE app setting from your function app.
``` 

I am using Linux with custom runtime and consumption plan.

The workaround is to use RBAC creds instead of PublishProfile.

https://github.com/Azure/functions-action/blob/master/src/handlers/contentPreparer.ts#L188

There is in readme how to use Service Principal creds -> https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential

**Comment by alexsorokoletov** [comment]
> Oh boy. I've been waiting for a while for Linux consumption plans to finally make their way to Canada. Thanks for sharing, I would not have known about this at all! Glad I didn't get the opportunity to waste my time.
> 
> This does seem sadly representative of the state of Azure Functions as a self-serve platform. My functions are written in TypeScript, built with GitHub Actions, and deployed to Azure. It's a full Microsoft stack, and every day it feels like a mess, with no real signs of hope.
> 
> Azure is not for the faint of heart. 😬

Would love to echo this comment and say it's 2023, we tried v3 and v4 and we got exactly same results as @aaronadamsCA 
https://github.com/Azure/functions-action/issues/58#issuecomment-778602558

**Comment by JAIS0N** [comment]
> Hey @maximivanov, I currently use this action to deploy Node.js function apps to Windows serverless (consumption) plans.
> 
> If you set `WEBSITE_RUN_FROM_PACKAGE=1` in the function app, and then deploy with this action, it runs from a package. My `wwwroot/` contains only `host.json`; my `data/SitePackages/` is full of ZIP files, one per deploy. My cold starts are fast, too. So it's definitely running from a ZIP file.
> 
> The team that supports this action seems to be spread way too thin, as evidenced by your question sitting unanswered for two months when the answer is literally just "yes."
> 
> I hope @github will consider giving @N-Usha enough resources to build this critical piece of infrastructure, because it needs a lot more attention than it gets today!


I was facing this error "When request Azure resource at PublishContent, zipDeploy : Failed to use" while deploying through GitHub workflows, When I checked my function app's, app configuration WEBSITE_RUN_FROM_PACKAGE was missing, when I added WEBSITE_RUN_FROM_PACKAGE=1, it deploys just fine without error. Can anyone elaborate on this.

**Comment by Techtacles** [comment]
> Inspired by @aaronadamsCA's success, I gave it a try and here are the results. Things are definitely not as bright in the Linux land. 😅
> 
> ### Linux Consumption
> ◉ I created a fresh Function App with `WEBSITE_RUN_FROM_PACKAGE=1` app setting. Published the code with the Github Action. All action's steps succeeded.
> 
> **Result:** code was not deployed. There are no files in the App Files section and no functions in the Functions in the Portal.
> 
> In fact, I realized I already opened an issue to update Azure docs to reflect the fact that Linux Consumption does not support `WEBSITE_RUN_FROM_PACKAGE=1`: [Azure/azure-functions-core-tools#2356](https://github.com/Azure/azure-functions-core-tools/issues/2356)
> 
> ◉ I then removed the `WEBSITE_RUN_FROM_PACKAGE=1` app setting and ran the Github Action again. All action's steps succeeded.
> 
> **Result:** the code was deployed. I assume the files were placed directly in the `/home/site/wwwroot`.
> 
> ### Linux Premium
> ◉ I created a new Function App with `WEBSITE_RUN_FROM_PACKAGE=1` app setting in a EP1 hosting plan. Published the code with the Github Action. All action's steps succeeded.
> 
> **Result:** code was deployed and `WEBSITE_RUN_FROM_PACKAGE=1` was respected. There is a zip file in `/home/data/SitePackages` as well as a `packagename.txt` referencing it.
> 
> ◉ I created a new Function App without `WEBSITE_RUN_FROM_PACKAGE=1` app setting in a EP1 hosting plan. Published the code with the Github Action. Run Azure Function action failed with the following error:
> 
> ```
> Running post deployment command(s)...
> Triggering recycle (preview mode disabled).
> Deployment successful.
> Error: Failed to deploy web package to App Service.
> Successfully updated deployment History at https://azfunccdgh-dev-function-app.scm.azurewebsites.net/api/deployments/9fd96845276b354c89a1ddee653c4a2a963babb81613163325529
> Error: Execution Exception (state: PublishContent) (step: Invocation)
> Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_33195088267481565.zip as ZipDeploy content
> Error:     Package deployment using ZIP Deploy failed. Refer logs for more details.
> Error: Deployment Failed!
> ```
> 
> _There was no error description in the referenced logs_
> 
> **Result:** despite the error, the code was deployed and worked. I could see files under `/home/site/wwwroot`. There was no `/home/data/SitePackages` directory.
> 
> I then ran the Action once again and there was no error that time. Not sure what it was.
> 
> ### Summary
> Linux Consumption: currently Functions Action deploys directly to the `wwwroot` folder. It should use `WEBSITE_RUN_FROM_PACKAGE=<url>` method by default instead (with configuration option to override if needed). Run from package is the recommended deployment method and it is the default in Azure Functions Core Tools.
> 
> Linux Premium: currently Functions Action respects the `WEBSITE_RUN_FROM_PACKAGE` setting. This makes sense. It's still inconsistent with Azure Functions Core Tools' defaults (`WEBSITE_RUN_FROM_PACKAGE=<url>`) though. But that's probably a part of a bigger discussion of unifying the deployment tooling.

Thank you so much. This worked. I was debugging this for about three days until I saw your comment. Thanks a lot.
