### ISSUE TITLE
.funcignore is (still) not respected

### ISSUE THREAD

**Issue by maximivanov** [Azure/functions-action#62]
Recreating https://github.com/Azure/functions-action/issues/36#issuecomment-748353831 as an issue for better visibility:

I gave this action a try and I can still see `.funcignore`d files deployed to the target host.

Here's the repo to reproduce: https://github.com/maximivanov/azure-functions-cd-github-actions

`respect-funcignore: true` is set on the functions-action in the workflow file.
Among others, `.funcignore` includes `.gitignore`.

Once cloud resources are provisioned (I use Terraform for that), I trigger the CD workflow in the repo.

**Expected:**
`.gitignore` is not deployed.

**Actual:** 
I can see `.gitignore` in the app files section in the Portal.

![Screen Shot 2020-12-18 at 22 34 42](https://user-images.githubusercontent.com/1759643/102667682-e4ca9380-4181-11eb-9f62-58ce2a8c352b.png)

@N-Usha @Hazhzeng 

Let me know if you need any further details. Thanks!

**Comment by aksm-ms** [comment]
@maximivanov Are you seeing any files from funcignore apart from ".gitignore" in the app files?

**Comment by maximivanov** [comment]
@aksm-ms it seems that funcignore has no effect on files prefixed with `.` (dot).

`randomfile.txt` was ignored
`randomfile-noextension` was ignored
`.randomfile-dotprefix` was deployed (I could see it in the App Files in Azure Portal).

**Comment by 20shivangi** [comment]
@N-Usha Should we mark this as an enhancement?
