### ISSUE TITLE
publish-profile : should be a valid XML.

### ISSUE THREAD

**Issue by Cherchercher** [Azure/functions-action#69]
steps to reproduct:
add key value pair to Vault,
retrieve value with key in Github workflow,
run function:

- name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ steps.secrets.outputs.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

Error: Execution Exception (state: ValidateParameter) (step: Invocation)
Error:   At ValidateParameter, publish-profile : should be a valid XML.
Error: Deployment Failed!

**Comment by Hazhzeng** [comment]
Hi @Cherchercher, your publish-profile is not a valid xml.

Please change ` steps.secrets.outputs.AZURE_FUNCTIONAPP_PUBLISH_PROFILE` to ` secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE`, and in your GitHub repo => Settings => Secrets => New repository secret => Add a "AZURE_FUNCTIONAPP_PUBLISH_PROFILE" secret with value from your publish profile.

![image](https://user-images.githubusercontent.com/48038149/113762729-c1463d00-96cd-11eb-9a2b-acd47468a1eb.png)

Let me know if you have any other questions.

**Comment by kanika1894** [comment]
Hoping this got resoloved. Feel free to open in case of any queries.
