### ISSUE TITLE
Support .PublishProfile with ZipDeploy section

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/functions-action#77]
The app service team slowly dropping the MSDeploy section from .publishSettings, currently causing an issue in ARC function app.
Our GitHub Action should be more resilient and able to parse the ZipDeploy section as well.
Here's an example of the new .publishSettings file:
```xml
<publishData>
    <publishProfile
        profileName="functionapp-name - Zip Deploy"
        publishMethod="ZipDeploy"
        publishUrl="functionapp-name.scm.arc-stamp.northcentralusstage.k4apps.io"
        userName="functionapp-username"
        userPWD="functionapp-password"
        destinationAppUrl="http://functionapp-name.arc-stamp.northcentralusstage.k4apps.io"
    />
</publishData>
```

**Comment by patelchandni** [comment]
This is covered in PR: https://github.com/Azure/functions-action/pull/123
