### ISSUE TITLE
Typo in output of Github Action for Azure Functions

### ISSUE THREAD

**Issue by stefanstranger** [Azure/functions-action#84]
I noticed a typo in the Github Action output for the Azure Functions.

![image](https://user-images.githubusercontent.com/2125385/119361089-8fa02a00-bcab-11eb-97ee-5ad48d9d7d2e.png)

Regards,
Stefan Stranger [MSFT]

**Comment by tomkerkhove** [comment]
The fix was just a PR away! #85
