### ISSUE TITLE
Support for functions that utilise identity auth to storage

### ISSUE THREAD

**Issue by damienpontifex** [Azure/functions-action#94]
As documented at https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connecting-to-host-storage-with-an-identity we can now use the settings `AzureWebJobsStorage__accountName` or `AzureWebJobsStorage__serviceUri` and the function managed identity to connect to storage (this is instead of `AzureWebJobsStorage` connection string)

There are a few warnings/assumptions in the codebase that this `AzureWebJobsStorage` property must exist when utilising this action.

It may also be the cause of an error I'm facing when deploying (relevant log section here)

```
Detected function app language: DotnetIsolated
Will directly deploy functions.zip as function app content.
Will use WEBSITE_RUN_FROM_PACKAGE to deploy since RBAC is detected and your function app is on Linux Consumption.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   At PublishContent, AzureWebjobsStorage : Failed to convert by semicolon delimeter.
Error:     Cannot read property 'trim' of undefined
Error:       TypeError: Cannot read property 'trim' of undefined
```

**Comment by amilochau** [comment]
Hi,

This is the last place where I still need infra secrets for the functions I deploy, from the Bicep templates to the application code.
That would be a great help to fully use Managed Identity!

**Comment by jbpaux** [comment]
+1 would be great to have it implemented :)

**Comment by patelchandni** [comment]
AzureWebJobsStorage is used for deployment artifacts when using server-side build in Linux Consumption, and if you enable this, you will need to deploy via [an external deployment package](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#using-website_run_from_package--url).
